server:
    port: 8080
    context-path: /api    
    
spring:
  http:      
    encoding.charset: UTF-8  
    encoding.enable: true  
    encoding.force: true        

multipart:
  maxFileSize: 3Mb  # Set the file size limit (default 1Mb). If you want to specify that files be unlimited set the multipart.maxFileSize property to -1.
  maxRequestSize: 10Mb  # Set the total request size for a multipart/form-data (default 10Mb)
  
# escape --> :, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @, ` 
api:
  upload.path: /tmp/upload 
  secretKey: '[5)JL\">jTD$B+!mP`tM|eS^E-_#03gHa?v{nC<wq'
  skipSign: true
  